# -*- coding: utf-8 -*-
"""hyper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xqley5PmA7LEQpoWWy-JEwW-F1L0H5CH
"""

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.ensemble import RandomForestRegressor

import matplotlib.pyplot as plt

import numpy as np
import pandas as pd

X = np.load("X_ecfp_full.npy")
y = pd.read_csv("y_targets_full.xls")

print("X shape:", X.shape) #(n_samples,n_bits)
print("y shape:", y.shape)
print("Target columns:", y.columns.tolist())

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("Train samples:", X_train.shape[0])
print("Test samples:", X_test.shape[0])

y_train_co2 = y_train['log_CO2']
y_test_co2 = y_test['log_CO2']

!pip install catboost

from catboost import CatBoostRegressor

from catboost import CatBoostRegressor
from sklearn.model_selection import RandomizedSearchCV

cat = CatBoostRegressor(
    loss_function="RMSE",
    random_seed=42,
    verbose=0
)

param_dist = {
    "iterations": [200, 300],
    "depth": [6, 8],
    "learning_rate": [0.05, 0.1],
    "l2_leaf_reg": [3, 5]
}

cat_search = RandomizedSearchCV(
    estimator=cat,
    param_distributions=param_dist,
    n_iter=6,
    scoring="r2",
    n_jobs=-1,
    verbose=2,
    random_state=42
)

cat_search.fit(X_train, y_train_co2)

best_cat = cat_search.best_estimator_

y_pred_cat = best_cat.predict(X_test)

from sklearn.metrics import r2_score, mean_absolute_error

print("CatBoost CO2 Test R2:", r2_score(y_test_co2, y_pred_cat))
print("CatBoost CO2 Test MAE:", mean_absolute_error(y_test_co2, y_pred_cat))

from xgboost import XGBRegressor

xgb = XGBRegressor(
    objective="reg:squarederror",
    random_state=42,
    n_jobs=-1
)

param_dist = {
    "n_estimators": [300, 500, 700],
    "max_depth": [4, 6, 8],
    "learning_rate": [0.03, 0.05, 0.1],
    "subsample": [0.8, 1.0],
    "colsample_bytree": [0.8, 1.0]
}

from sklearn.model_selection import RandomizedSearchCV

xgb_search = RandomizedSearchCV(
    estimator=xgb,
    param_distributions=param_dist,
    n_iter=15,
    cv=5,
    scoring="r2",
    n_jobs=-1,
    verbose=2,
    random_state=42
)

xgb_search.fit(X_train, y_train_co2)

best_xgb = xgb_search.best_estimator_

y_pred_xgb = best_xgb.predict(X_test)

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

r2_xgb = r2_score(y_test_co2, y_pred_xgb)

mae_xgb = mean_absolute_error(y_test_co2, y_pred_xgb)

print(f"XGBoost CO2 Test R2: {r2_xgb:.3f}")

print(f"XGBoost CO2 Test MAE: {mae_xgb:.3f}")

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV

rf = RandomForestRegressor(
    random_state=42,
    n_jobs=-1
)

param_dist = {
    "n_estimators": [200, 300, 400],
    "max_depth": [None, 20],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2],
    "max_features": ["sqrt"]
}

random_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_dist,
    n_iter=10,        # 🔑 CO2-only → enough
    cv=5,
    scoring="r2",
    n_jobs=-1,
    verbose=2,
    random_state=42
)

random_search.fit(X_train, y_train_co2)

best_rf_co2 = random_search.best_estimator_

print("Best hyperparameters:")
print(random_search.best_params_)

print("Best CV R2 score:")
print(random_search.best_score_)

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

y_pred_co2 = best_rf_co2.predict(X_test)

r2 = r2_score(y_test_co2, y_pred_co2)

mae = mean_absolute_error(y_test_co2, y_pred_co2)

print(f"CO2 Test R2: {r2:.3f}")

print(f"CO2 Test MAE: {mae:.3f}")

import matplotlib.pyplot as plt
import numpy as np

# Get importance scores
xgb_importance = best_xgb.feature_importances_

# Get top 20 features
top_idx = np.argsort(xgb_importance)[-20:]

plt.figure(figsize=(8,6))
plt.barh(range(20), xgb_importance[top_idx])
plt.yticks(range(20), [f"ECFP_{i}" for i in top_idx])
plt.xlabel("Feature importance")
plt.title("Top 20 XGBoost feature importances for CO₂ permeability")
plt.show()

cat_importance = best_cat.get_feature_importance()

top_idx = np.argsort(cat_importance)[-20:]

plt.figure(figsize=(8,6))
plt.barh(range(20), cat_importance[top_idx])
plt.yticks(range(20), [f"ECFP_{i}" for i in top_idx])
plt.xlabel("Feature importance")
plt.title("Top 20 CatBoost feature importances for CO₂ permeability")
plt.show()

!pip install shap

import shap

explainer_xgb = shap.TreeExplainer(best_xgb)

# Use a subset to keep it fast
X_sample = X_train[:500]

shap_values_xgb = explainer_xgb.shap_values(X_sample)

shap.summary_plot(
    shap_values_xgb,
    X_sample,
    feature_names=[f"ECFP_{i}" for i in range(X.shape[1])]
)

from catboost import Pool

shap_values_cat = best_cat.get_feature_importance(
    data=Pool(X_sample),
    type="ShapValues"
)


shap_values_cat = shap_values_cat[:, :-1]

shap.summary_plot(
    shap_values_cat,
    X_sample,
    feature_names=[f"ECFP_{i}" for i in range(X.shape[1])]
)

import numpy as np

# Individual tree predictions
rf_tree_preds = np.array([
    tree.predict(X_test) for tree in best_rf_co2.estimators_
])

# Mean prediction
rf_mean_pred = rf_tree_preds.mean(axis=0)

# Uncertainty = standard deviation across trees
rf_std_pred = rf_tree_preds.std(axis=0)

print("RF prediction shape:", rf_mean_pred.shape)
print("RF uncertainty shape:", rf_std_pred.shape)

import matplotlib.pyplot as plt

plt.figure(figsize=(6,5))
plt.errorbar(
    y_test["log_CO2"],
    rf_mean_pred,
    yerr=rf_std_pred,
    fmt='o',
    alpha=0.5
)
plt.plot(
    [y_test["log_CO2"].min(), y_test["log_CO2"].max()],
    [y_test["log_CO2"].min(), y_test["log_CO2"].max()],
    'r--'
)

plt.xlabel("True log CO₂ permeability")
plt.ylabel("Predicted log CO₂ permeability")
plt.title("Random Forest Prediction with Uncertainty")
plt.show()

from sklearn.utils import resample
import numpy as np

# number of bootstrap models
n_models = 20
xgb_preds = []

# get tuned parameters safely
best_params = best_xgb.get_params()

# remove conflicting keys
for key in ["objective", "random_state", "n_jobs"]:
    best_params.pop(key, None)

for i in range(n_models):

    # bootstrap resample
    X_bs, y_bs = resample(
        X_train,
        y_train_co2,
        random_state=100 + i
    )

    # rebuild model with tuned params
    model = XGBRegressor(
        **best_params,
        objective="reg:squarederror",
        random_state=100 + i,
        n_jobs=-1
    )

    model.fit(X_bs, y_bs)

    # predict
    xgb_preds.append(model.predict(X_test))

# convert to array
xgb_preds = np.array(xgb_preds)

# mean & uncertainty
xgb_mean_pred = xgb_preds.mean(axis=0)
xgb_std_pred  = xgb_preds.std(axis=0)

print("XGBoost uncertainty computed successfully")

print("Mean uncertainty:", xgb_std_pred.mean())
print("Max uncertainty:", xgb_std_pred.max())

plt.figure(figsize=(6,5))
plt.errorbar(
    y_test["log_CO2"],
    xgb_mean_pred,
    yerr=xgb_std_pred,
    fmt='o',
    alpha=0.5
)
plt.plot(
    [y_test["log_CO2"].min(), y_test["log_CO2"].max()],
    [y_test["log_CO2"].min(), y_test["log_CO2"].max()],
    'r--'
)

plt.xlabel("True log CO₂ permeability")
plt.ylabel("Predicted log CO₂ permeability")
plt.title("XGBoost Prediction with Uncertainty (Bootstrap)")
plt.show()

import numpy as np
import pandas as pd
from catboost import CatBoostRegressor
from sklearn.utils import resample

from sklearn.utils import resample
import numpy as np
from catboost import CatBoostRegressor

n_models = 20
cat_preds = []

# get tuned parameters
best_params = best_cat.get_params()

# remove conflicting keys
for key in ["random_seed", "thread_count", "verbose"]:
    best_params.pop(key, None)

for i in range(n_models):

    X_bs, y_bs = resample(
        X_train,
        y_train_co2,
        random_state=200 + i
    )

    model = CatBoostRegressor(
        **best_params,
        random_seed=200 + i,
        verbose=0
    )

    model.fit(X_bs, y_bs)

    cat_preds.append(model.predict(X_test))

cat_preds = np.array(cat_preds)

cat_mean_pred = cat_preds.mean(axis=0)
cat_std_pred  = cat_preds.std(axis=0)

print("CatBoost uncertainty computed successfully")

print("Mean uncertainty:", cat_std_pred.mean())
print("Max uncertainty:", cat_std_pred.max())

plt.figure(figsize=(6,5))
plt.errorbar(
    y_test["log_CO2"],
    cat_mean_pred,
    yerr=cat_std_pred,
    fmt='o',
    alpha=0.5
)

plt.plot(
    [y_test["log_CO2"].min(), y_test["log_CO2"].max()],
    [y_test["log_CO2"].min(), y_test["log_CO2"].max()],
    'r--'
)

plt.xlabel("True log CO₂ permeability")
plt.ylabel("Predicted log CO₂ permeability")
plt.title("CatBoost Prediction with Uncertainty (Bootstrap)")
plt.show()

import joblib

joblib.dump(best_xgb, "final_xgb_surrogate_CO2.pkl") #save the best model to disk

import pandas as pd

original_data = pd.read_excel("dataset.xls") #load the dataset


print(original_data.columns)

print("X shape:", X.shape) #print the feature matrix

filtered_data = original_data[
    original_data[["CO2", "N2", "O2"]].notna().all(axis=1) # filter the rows with gas data
].reset_index(drop=True)

print(len(filtered_data))

assert len(filtered_data) == X.shape[0]

results_all = pd.DataFrame({ # create a new table with values smiles,type ,predict co2
    "SMILES": filtered_data["SMILES"].values,
    "Type": filtered_data["Type"].values,
    "Pred_log_CO2": best_xgb.predict(X)
})

results_all["True_log_CO2"] = np.log10(filtered_data["CO2"].values) #add true value to new table

results_all.to_csv("xgb_predictions_all_polymers.csv", index=False) #add result to csv file

results_all.groupby("Type").size() #group the res by Type

results_all.columns

exp_data = results_all[results_all["Type"] == "Experimental"]
ga_data  = results_all[results_all["Type"] == "Genetic Algorithm"] #grp them by type

results_all["Pred_log_CO2"].isna().sum() # check if NA is present

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(7,5))

sns.kdeplot(exp_data["Pred_log_CO2"], label="Experimental", fill=True)
sns.kdeplot(ga_data["Pred_log_CO2"], label="GA-generated", fill=True) #kde is kernel density estimation is a smooth distribution function

plt.xlabel("Predicted log CO₂ Permeability")
plt.ylabel("Density")
plt.legend()
plt.title("Distribution of Predicted CO₂ Permeability")
plt.tight_layout()
plt.show()

# Train or load N2 model (same hyperparameters)
final_xgb_N2 = XGBRegressor(
    n_estimators=400,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    min_child_weight=1,
    objective="reg:squarederror",
    random_state=42,
    n_jobs=-1
)

final_xgb_N2.fit(X, y["log_N2"]) # train a tuned xgboost model for predicting log_n2

# Predict for ALL polymers
results_all["Pred_log_N2"] = final_xgb_N2.predict(X)

results_all["Pred_log_CO2_N2"] = (
    results_all["Pred_log_CO2"] - results_all["Pred_log_N2"] # predict selectivity
)

results_all["Is_GA"] = (results_all["Type"] == "Genetic Algorithm").astype(int) # create a label 0- experimental and  1- ga

plt.figure(figsize=(6,5))

sc = plt.scatter(
    results_all["Pred_log_CO2"], # permeability
    results_all["Pred_log_CO2_N2"], # selectivity
    c=results_all["Is_GA"],
    cmap="coolwarm",
    alpha=0.7
)

plt.xlabel("Predicted log CO₂ Permeability")
plt.ylabel("Predicted log(CO₂/N₂) Selectivity")
plt.title("Permeability–Selectivity Trade-off")

cbar = plt.colorbar(sc)
cbar.set_ticks([0, 1])
cbar.set_ticklabels(["Experimental", "GA-generated"])

plt.tight_layout()
plt.show()

from xgboost import XGBRegressor



# Train N2 model
xgb_n2 = XGBRegressor( # run a tuned model to predict log_n2 and log_o2
    n_estimators=400,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    min_child_weight=1,
    objective="reg:squarederror",
    random_state=42,
    n_jobs=-1
)

xgb_n2.fit(X, y["log_N2"])


# Train O2 model
xgb_o2 = XGBRegressor(
    n_estimators=400,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    min_child_weight=1,
    objective="reg:squarederror",
    random_state=42,
    n_jobs=-1
)

xgb_o2.fit(X, y["log_O2"])

pred_co2 = best_xgb.predict(X)
pred_n2  = xgb_n2.predict(X)
pred_o2  = xgb_o2.predict(X)

selectivity_co2_n2 = pred_co2 - pred_n2
selectivity_co2_o2 = pred_co2 - pred_o2 # selectivity

import pandas as pd

results_all = pd.DataFrame({ # create a table
    "Pred_log_CO2": pred_co2,
    "Pred_log_N2": pred_n2,
    "Pred_log_O2": pred_o2,
    "Pred_log_CO2_N2": selectivity_co2_n2,
    "Pred_log_CO2_O2": selectivity_co2_o2
})

import matplotlib.pyplot as plt

plt.figure(figsize=(6,5))

plt.scatter(
    results_all["Pred_log_CO2"], # x -axis-permeability
    results_all["Pred_log_CO2_N2"], # y-axis - selectivity
    alpha=0.6
)

plt.xlabel("Predicted log CO₂ Permeability")
plt.ylabel("Predicted log (CO₂/N₂) Selectivity")
plt.title("Permeability–Selectivity Trade-off")

plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

# Define thresholds (you can adjust)
high_perm = results_all["Pred_log_CO2"] > 3 # selecting candidates with high permeability (1000 barrer)
high_sel  = results_all["Pred_log_CO2_N2"] > 1.5 # selecting candidates with high selectivity (31.6)

top_candidates = results_all[high_perm & high_sel]

print("Number of top candidates:", len(top_candidates))

top_candidates.sort_values(
    by=["Pred_log_CO2", "Pred_log_CO2_N2"],
    ascending=False
).head(10)

import numpy as np
import matplotlib.pyplot as plt

# Use your predicted values
x = results_all["Pred_log_CO2"] # permeability
y = results_all["Pred_log_CO2"] - results_all["Pred_log_N2"] # selectivity

plt.figure(figsize=(7,6))

# Scatter plot
plt.scatter(
    x,
    y,
    alpha=0.6,
    s=20
)

# -----------------------------
# Robeson Upper Bound
# -----------------------------

# Create smooth range of permeability values
x_line = np.linspace(x.min(), x.max(), 200) # each dot as one polymer

# Robeson 2008 approximation
robeson_line = 1.0 - 0.5 * x_line #linear  approximation

plt.plot(
    x_line,
    robeson_line,
    'r--',
    linewidth=2,
    label="Robeson Upper Bound (2008)"
)

plt.xlabel("Predicted log CO₂ Permeability")
plt.ylabel("Predicted log(CO₂/N₂) Selectivity")
plt.title("Permeability–Selectivity Trade-off with Robeson Upper Bound")
plt.legend()
plt.tight_layout()
plt.show()

# Robeson bound equation
def robeson_bound(x):
    return 1.0 - 0.5 * x #1=intercept 0.5=slope

# Calculate selectivity
results_all["Pred_log_Selectivity"] = (
    results_all["Pred_log_CO2"] - results_all["Pred_log_N2"]
)

# Calculate Robeson limit for each sample
results_all["Robeson_limit"] = robeson_bound(results_all["Pred_log_CO2"])

# Distance from bound
results_all["Distance_from_bound"] = (
    results_all["Pred_log_Selectivity"] - results_all["Robeson_limit"] #>0 above bound else below bound
)

# Identify promising candidates
top_candidates = results_all[
    results_all["Distance_from_bound"] > 0
]

print("Number of candidates above Robeson bound:", len(top_candidates))
top_candidates.head()

from sklearn.utils import resample
from xgboost import XGBRegressor
import numpy as np

n_models = 20 # multiple models # distribution of predictions
xgb_preds = []

# get tuned parameters
best_params = best_xgb.get_params()

# remove conflicting keys
for key in ["objective", "random_state", "n_jobs"]:
    best_params.pop(key, None)

for i in range(n_models):

    # bootstrap resampling from training set
    X_bs, y_bs = resample( # create a new training dataset each time by samling with replacement and using diff data distribution
        X_train,
        y_train_co2,
        random_state=100 + i
    )

    # rebuild model
    model = XGBRegressor(
        **best_params,
        objective="reg:squarederror",
        random_state=100 + i,
        n_jobs=-1
    )

    model.fit(X_bs, y_bs)

    # predict FULL dataset
    preds = model.predict(X)
    xgb_preds.append(preds)

# convert to array
xgb_preds = np.array(xgb_preds) #[20 models,N_samples]

# compute mean and uncertainty
mean_co2 = xgb_preds.mean(axis=0)
uncertainty_co2 = xgb_preds.std(axis=0)

results_all["Pred_log_CO2"] = mean_co2 #stores the result
results_all["Uncertainty_CO2"] = uncertainty_co2

threshold = results_all["Uncertainty_CO2"].quantile(0.75)# 75% of the uncertainty 25% of the unceratinty are removed

robust_candidates = results_all[
    results_all["Uncertainty_CO2"] < threshold # keep only robust candidates (keep a polymer when a model is confident)
]

top_threshold = results_all["Pred_log_CO2"].quantile(0.95) #select top 5% performers

top_candidates = results_all[
    results_all["Pred_log_CO2"] > top_threshold # high-permeability polymers
]

# Robust + High Performance +low uncertain
final_candidates = top_candidates[
    top_candidates["Uncertainty_CO2"] < threshold
]

final_candidates.head()

robust_candidates = final_candidates[
    final_candidates["Pred_log_Selectivity"] > final_candidates["Robeson_limit"] #above robeson limit
]

robust_candidates.head()

final_candidates["Score"] = (
    final_candidates["Pred_log_CO2"] +
    final_candidates["Pred_log_Selectivity"] -
    5 * final_candidates["Uncertainty_CO2"]
)

top_ranked = final_candidates.sort_values("Score", ascending=False)#high to low

top_ranked.head(10)

# ============================================================
# FINAL OPTIMIZATION PIPELINE (Correct Pareto Implementation)
# ============================================================

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# ------------------------------------------------------------
# 1️⃣  Correct Pareto-efficient function
# ------------------------------------------------------------
def is_pareto_efficient(points):
    """
    Returns boolean mask of Pareto-efficient points.
    Assumes larger values are better for all objectives.
    """
    n_points = points.shape[0]
    is_efficient = np.ones(n_points, dtype=bool)

    for i in range(n_points):
        if not is_efficient[i]:
            continue

        # A point j dominates i if:
        # j >= i in ALL objectives
        # AND j > i in at least one objective
        dominates = np.all(points >= points[i], axis=1) & \
                    np.any(points > points[i], axis=1)

        is_efficient[dominates] = False
        is_efficient[i] = True

    return is_efficient


# ------------------------------------------------------------
# 2️⃣  Prepare optimization matrix
#     (HIGH perm, HIGH selectivity, LOW uncertainty)
# ------------------------------------------------------------

cost_matrix = np.column_stack([
    results_all["Pred_log_CO2"],
    results_all["Pred_log_Selectivity"],
    -results_all["Uncertainty_CO2"]  # minimize uncertainty
])


# ------------------------------------------------------------
# 3️⃣  Extract Pareto-optimal candidates
# ------------------------------------------------------------

pareto_mask = is_pareto_efficient(cost_matrix)
pareto_candidates = results_all[pareto_mask]

print("Total Pareto-optimal candidates:", len(pareto_candidates))


# ------------------------------------------------------------
# 4️⃣  Keep only those above Robeson upper bound
# ------------------------------------------------------------

pareto_above = pareto_candidates[
    pareto_candidates["Distance_from_bound"] > 0
]

print("Pareto candidates above Robeson bound:", len(pareto_above))


# ------------------------------------------------------------
# 5️⃣  Filter low-uncertainty (robust candidates)
# ------------------------------------------------------------

unc_threshold = pareto_above["Uncertainty_CO2"].quantile(0.75)

robust_pareto = pareto_above[
    pareto_above["Uncertainty_CO2"] < unc_threshold
]

print("Robust Pareto candidates:", len(robust_pareto))


# ------------------------------------------------------------
# 6️⃣  Composite scoring (normalized multi-objective ranking)
# ------------------------------------------------------------

scaler = MinMaxScaler()

score_df = robust_pareto.copy()

score_df["Norm_CO2"] = scaler.fit_transform(
    score_df[["Pred_log_CO2"]]
)

score_df["Norm_Selectivity"] = scaler.fit_transform(
    score_df[["Pred_log_Selectivity"]]
)

score_df["Norm_Distance"] = scaler.fit_transform(
    score_df[["Distance_from_bound"]]
)

# Lower uncertainty is better → invert
score_df["Norm_Uncertainty"] = 1 - scaler.fit_transform(
    score_df[["Uncertainty_CO2"]]
)

score_df["Composite_Score"] = (
    0.35 * score_df["Norm_CO2"] +
    0.35 * score_df["Norm_Selectivity"] +
    0.20 * score_df["Norm_Distance"] +
    0.10 * score_df["Norm_Uncertainty"]
)

top_final = score_df.sort_values(
    by="Composite_Score",
    ascending=False
).head(20)

print("\nTop 20 Optimized Membrane Candidates:")
display(top_final[[
    "Pred_log_CO2",
    "Pred_log_Selectivity",
    "Distance_from_bound",
    "Uncertainty_CO2",
    "Composite_Score"
]])

# ------------------------------------------------------------
# 7️⃣  Save final results
# ------------------------------------------------------------

top_final.to_csv("Top_20_Optimized_Membranes.csv", index=False)
pareto_candidates.to_csv("Pareto_Optimal_Membranes.csv", index=False)
robust_pareto.to_csv("Robust_Pareto_Membranes.csv", index=False)

print("\nOptimization pipeline completed successfully.")

plt.figure(figsize=(7,6))

plt.scatter(
    results_all["Pred_log_CO2"],
    results_all["Pred_log_Selectivity"],
    alpha=0.3,
    label="All Polymers"
)

plt.scatter(
    pareto_candidates["Pred_log_CO2"],
    pareto_candidates["Pred_log_Selectivity"],
    color="red",
    label="Pareto Front"
)

plt.xlabel("Predicted log CO₂ Permeability")
plt.ylabel("Predicted log(CO₂/N₂) Selectivity")
plt.title("Pareto-Optimal Membrane Candidates")
plt.legend()
plt.show()

from sklearn.utils import resample
from xgboost import XGBRegressor
import numpy as np

n_models = 20
xgb_preds_test = []

best_params = best_xgb.get_params()

# remove conflicting keys
for key in ["objective", "random_state", "n_jobs"]:
    best_params.pop(key, None)

for i in range(n_models):

    X_bs, y_bs = resample(
        X_train,
        y_train_co2,
        random_state=100 + i
    )

    model = XGBRegressor(
        **best_params,
        objective="reg:squarederror",
        random_state=100 + i,
        n_jobs=-1
    )

    model.fit(X_bs, y_bs)

    preds_test = model.predict(X_test)
    xgb_preds_test.append(preds_test)

xgb_preds_test = np.array(xgb_preds_test)

mean_pred = xgb_preds_test.mean(axis=0)
uncertainty = xgb_preds_test.std(axis=0)

residuals = y_test_co2.values - mean_pred
abs_residuals = np.abs(residuals)

within_1sigma = np.mean(abs_residuals <= uncertainty)
within_2sigma = np.mean(abs_residuals <= 2 * uncertainty)

print(f"Percentage within ±1σ: {within_1sigma*100:.2f}%")
print(f"Percentage within ±2σ: {within_2sigma*100:.2f}%")

# ===============================
# Uncertainty Calibration
# ===============================

# Compute scale factor
scale_factor = np.mean(abs_residuals) / np.mean(uncertainty)

print("Uncertainty scale factor:", scale_factor)

# Calibrate uncertainty
uncertainty_calibrated = scale_factor * uncertainty

# Recompute coverage
within_1sigma_cal = np.mean(abs_residuals <= uncertainty_calibrated)
within_2sigma_cal = np.mean(abs_residuals <= 2 * uncertainty_calibrated)

print(f"Calibrated within 1σ: {within_1sigma_cal*100:.2f}%")
print(f"Calibrated within 2σ: {within_2sigma_cal*100:.2f}%")

# Apply calibration globally
results_all["Uncertainty_CO2"] = (
    scale_factor * results_all["Uncertainty_CO2"]
)

plt.figure(figsize=(6,5))

plt.scatter(uncertainty_calibrated, abs_residuals, alpha=0.6)


plt.xlabel("Predicted Uncertainty (σ)")
plt.ylabel("Absolute Residual |y - ŷ|")
plt.title("Uncertainty Calibration: Residual vs Predicted σ")

plt.tight_layout()
plt.show()

from sklearn.model_selection import learning_curve # how model learns with increasing data to predict underfit,overfti
from sklearn.metrics import make_scorer, r2_score

train_sizes, train_scores, val_scores = learning_curve(
    best_xgb,
    X_train,
    y_train_co2,
    cv=5,
    scoring="r2",
    train_sizes=np.linspace(0.1, 1.0, 8),
    n_jobs=-1
)

train_mean = train_scores.mean(axis=1)
val_mean = val_scores.mean(axis=1)

plt.figure(figsize=(6,5))

plt.plot(train_sizes, train_mean, 'o-', label="Training R²")
plt.plot(train_sizes, val_mean, 'o-', label="Validation R²")

plt.xlabel("Training Sample Size")
plt.ylabel("R² Score")
plt.title("Learning Curve (XGBoost - CO₂)")
plt.legend()

plt.tight_layout()
plt.show()

# Normalize metrics for fair scoring
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() #noramlize so that one do not dominate the other

score_df = robust_pareto.copy()

score_df[["Norm_CO2"]] = scaler.fit_transform(
    score_df[["Pred_log_CO2"]]
)

score_df[["Norm_Selectivity"]] = scaler.fit_transform(
    score_df[["Pred_log_Selectivity"]]
)

score_df[["Norm_Distance"]] = scaler.fit_transform(
    score_df[["Distance_from_bound"]]
)

# Lower uncertainty is better → invert it because scaler makes larger value
score_df[["Norm_Uncertainty"]] = 1 - scaler.fit_transform(
    score_df[["Uncertainty_CO2"]]
)

score_df["Composite_Score"] = (
    0.35 * score_df["Norm_CO2"] + # 35% importance to norm_co2
    0.35 * score_df["Norm_Selectivity"] +
    0.20 * score_df["Norm_Distance"] +
    0.10 * score_df["Norm_Uncertainty"]
)

top_final = score_df.sort_values(
    by="Composite_Score",
    ascending=False
).head(20)

top_final.reset_index(drop=True, inplace=True)

top_final.head()

report_table = top_final[[
    "Pred_log_CO2",
    "Pred_log_Selectivity",
    "Distance_from_bound",
    "Uncertainty_CO2",
    "Composite_Score"
]]

report_table

report_table.to_csv("Top_20_Optimized_Membranes.csv", index=False)

# Assume membrane thickness (m)
thickness = 100e-9  # 100 nm

# Convert log permeability to permeability
P_CO2 = 10 ** results_all["Pred_log_CO2"]

# Compute permeance
permeance_CO2 = P_CO2 / thickness

results_all["Permeance_CO2"] = permeance_CO2

results_all["TechnoEconomic_Index"] = (
    0.5 * (results_all["Permeance_CO2"] / results_all["Permeance_CO2"].max()) +
    0.4 * (results_all["Pred_log_Selectivity"] / results_all["Pred_log_Selectivity"].max()) -
    0.1 * (results_all["Uncertainty_CO2"] / results_all["Uncertainty_CO2"].max())
)

results_all["TechnoEconomic_Index"] = (
    0.5 * (results_all["Permeance_CO2"] / results_all["Permeance_CO2"].max()) +
    0.4 * (results_all["Pred_log_Selectivity"] / results_all["Pred_log_Selectivity"].max()) -
    0.1 * (results_all["Uncertainty_CO2"] / results_all["Uncertainty_CO2"].max())
)

plt.figure(figsize=(6,5))

# Plot all polymers
plt.scatter(
    results_all["Permeance_CO2"],
    results_all["Pred_log_Selectivity"],
    c=results_all["TechnoEconomic_Index"],
    cmap="viridis",
    alpha=0.6
)

# Highlight top candidates
top = results_all.sort_values("TechnoEconomic_Index", ascending=False).head(10)

plt.scatter(
    top["Permeance_CO2"],
    top["Pred_log_Selectivity"],
    color="red",
    s=120,
    edgecolor="black",
    label="Top candidates"
)

plt.xscale("log")

plt.colorbar(label="Techno-Economic Index")
plt.xlabel("CO₂ Permeance (log scale)")
plt.ylabel("log(CO₂/N₂) Selectivity")
plt.title("Screening-Level Feasibility Map")

plt.legend()
plt.show()

top = results_all.sort_values("TechnoEconomic_Index", ascending=False).head(10)

print(top[[
    "Permeance_CO2",
    "Pred_log_Selectivity",
    "TechnoEconomic_Index"
]])

