# -*- coding: utf-8 -*-
"""hyper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xqley5PmA7LEQpoWWy-JEwW-F1L0H5CH
"""

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.ensemble import RandomForestRegressor

import matplotlib.pyplot as plt

import numpy as np
import pandas as pd

X = np.load("X_ecfp_full.npy")
y = pd.read_csv("y_targets_full.xls")

print("X shape:", X.shape) #(n_samples,n_bits)
print("y shape:", y.shape)
print("Target columns:", y.columns.tolist())

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("Train samples:", X_train.shape[0])
print("Test samples:", X_test.shape[0])

y_train_co2 = y_train['log_CO2']
y_test_co2 = y_test['log_CO2']

!pip install catboost

from catboost import CatBoostRegressor

from catboost import CatBoostRegressor
from sklearn.model_selection import RandomizedSearchCV

cat = CatBoostRegressor(
    loss_function="RMSE",
    random_seed=42,
    verbose=0
)

param_dist = {
    "iterations": [200, 300],
    "depth": [6, 8],
    "learning_rate": [0.05, 0.1],
    "l2_leaf_reg": [3, 5]
}

cat_search = RandomizedSearchCV(
    estimator=cat,
    param_distributions=param_dist,
    n_iter=6,
    scoring="r2",
    n_jobs=-1,
    verbose=2,
    random_state=42
)

cat_search.fit(X_train, y_train_co2)

best_cat = cat_search.best_estimator_

y_pred_cat = best_cat.predict(X_test)

from sklearn.metrics import r2_score, mean_absolute_error

print("CatBoost CO2 Test R2:", r2_score(y_test_co2, y_pred_cat))
print("CatBoost CO2 Test MAE:", mean_absolute_error(y_test_co2, y_pred_cat))

from xgboost import XGBRegressor

xgb = XGBRegressor(
    objective="reg:squarederror",
    random_state=42,
    n_jobs=-1
)

param_dist = {
    "n_estimators": [300, 500, 700],
    "max_depth": [4, 6, 8],
    "learning_rate": [0.03, 0.05, 0.1],
    "subsample": [0.8, 1.0],
    "colsample_bytree": [0.8, 1.0]
}

from sklearn.model_selection import RandomizedSearchCV

xgb_search = RandomizedSearchCV(
    estimator=xgb,
    param_distributions=param_dist,
    n_iter=15,
    cv=5,
    scoring="r2",
    n_jobs=-1,
    verbose=2,
    random_state=42
)

xgb_search.fit(X_train, y_train_co2)

best_xgb = xgb_search.best_estimator_

y_pred_xgb = best_xgb.predict(X_test)

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

r2_xgb = r2_score(y_test_co2, y_pred_xgb)

mae_xgb = mean_absolute_error(y_test_co2, y_pred_xgb)

print(f"XGBoost CO2 Test R2: {r2_xgb:.3f}")

print(f"XGBoost CO2 Test MAE: {mae_xgb:.3f}")

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV

rf = RandomForestRegressor(
    random_state=42,
    n_jobs=-1
)

param_dist = {
    "n_estimators": [200, 300, 400],
    "max_depth": [None, 20],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2],
    "max_features": ["sqrt"]
}

random_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_dist,
    n_iter=10,        # 🔑 CO2-only → enough
    cv=5,
    scoring="r2",
    n_jobs=-1,
    verbose=2,
    random_state=42
)

random_search.fit(X_train, y_train_co2)

best_rf_co2 = random_search.best_estimator_

print("Best hyperparameters:")
print(random_search.best_params_)

print("Best CV R2 score:")
print(random_search.best_score_)

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

y_pred_co2 = best_rf_co2.predict(X_test)

r2 = r2_score(y_test_co2, y_pred_co2)

mae = mean_absolute_error(y_test_co2, y_pred_co2)

print(f"CO2 Test R2: {r2:.3f}")

print(f"CO2 Test MAE: {mae:.3f}")

import matplotlib.pyplot as plt
import numpy as np

# Get importance scores
xgb_importance = best_xgb.feature_importances_

# Get top 20 features
top_idx = np.argsort(xgb_importance)[-20:]

plt.figure(figsize=(8,6))
plt.barh(range(20), xgb_importance[top_idx])
plt.yticks(range(20), [f"ECFP_{i}" for i in top_idx])
plt.xlabel("Feature importance")
plt.title("Top 20 XGBoost feature importances for CO₂ permeability")
plt.show()

cat_importance = best_cat.get_feature_importance()

top_idx = np.argsort(cat_importance)[-20:]

plt.figure(figsize=(8,6))
plt.barh(range(20), cat_importance[top_idx])
plt.yticks(range(20), [f"ECFP_{i}" for i in top_idx])
plt.xlabel("Feature importance")
plt.title("Top 20 CatBoost feature importances for CO₂ permeability")
plt.show()

!pip install shap

import shap

explainer_xgb = shap.TreeExplainer(best_xgb)

# Use a subset to keep it fast
X_sample = X_train[:500]

shap_values_xgb = explainer_xgb.shap_values(X_sample)

shap.summary_plot(
    shap_values_xgb,
    X_sample,
    feature_names=[f"ECFP_{i}" for i in range(X.shape[1])]
)

from catboost import Pool

shap_values_cat = best_cat.get_feature_importance(
    data=Pool(X_sample),
    type="ShapValues"
)


shap_values_cat = shap_values_cat[:, :-1]

shap.summary_plot(
    shap_values_cat,
    X_sample,
    feature_names=[f"ECFP_{i}" for i in range(X.shape[1])]
)

import numpy as np

# Individual tree predictions
rf_tree_preds = np.array([
    tree.predict(X_test) for tree in best_rf_co2.estimators_
])

# Mean prediction
rf_mean_pred = rf_tree_preds.mean(axis=0)

# Uncertainty = standard deviation across trees
rf_std_pred = rf_tree_preds.std(axis=0)

print("RF prediction shape:", rf_mean_pred.shape)
print("RF uncertainty shape:", rf_std_pred.shape)

import matplotlib.pyplot as plt

plt.figure(figsize=(6,5))
plt.errorbar(
    y_test["log_CO2"],
    rf_mean_pred,
    yerr=rf_std_pred,
    fmt='o',
    alpha=0.5
)
plt.plot(
    [y_test["log_CO2"].min(), y_test["log_CO2"].max()],
    [y_test["log_CO2"].min(), y_test["log_CO2"].max()],
    'r--'
)

plt.xlabel("True log CO₂ permeability")
plt.ylabel("Predicted log CO₂ permeability")
plt.title("Random Forest Prediction with Uncertainty")
plt.show()

from sklearn.utils import resample
import numpy as np

# number of bootstrap models
n_models = 20
xgb_preds = []

# get tuned parameters safely
best_params = best_xgb.get_params()

# remove conflicting keys
for key in ["objective", "random_state", "n_jobs"]:
    best_params.pop(key, None)

for i in range(n_models):

    # bootstrap resample
    X_bs, y_bs = resample(
        X_train,
        y_train_co2,
        random_state=100 + i
    )

    # rebuild model with tuned params
    model = XGBRegressor(
        **best_params,
        objective="reg:squarederror",
        random_state=100 + i,
        n_jobs=-1
    )

    model.fit(X_bs, y_bs)

    # predict
    xgb_preds.append(model.predict(X_test))

# convert to array
xgb_preds = np.array(xgb_preds)

# mean & uncertainty
xgb_mean_pred = xgb_preds.mean(axis=0)
xgb_std_pred  = xgb_preds.std(axis=0)

print("XGBoost uncertainty computed successfully")

print("Mean uncertainty:", xgb_std_pred.mean())
print("Max uncertainty:", xgb_std_pred.max())

plt.figure(figsize=(6,5))
plt.errorbar(
    y_test["log_CO2"],
    xgb_mean_pred,
    yerr=xgb_std_pred,
    fmt='o',
    alpha=0.5
)
plt.plot(
    [y_test["log_CO2"].min(), y_test["log_CO2"].max()],
    [y_test["log_CO2"].min(), y_test["log_CO2"].max()],
    'r--'
)

plt.xlabel("True log CO₂ permeability")
plt.ylabel("Predicted log CO₂ permeability")
plt.title("XGBoost Prediction with Uncertainty (Bootstrap)")
plt.show()

import numpy as np
import pandas as pd
from catboost import CatBoostRegressor
from sklearn.utils import resample

from sklearn.utils import resample
import numpy as np
from catboost import CatBoostRegressor

n_models = 20
cat_preds = []

# get tuned parameters
best_params = best_cat.get_params()

# remove conflicting keys
for key in ["random_seed", "thread_count", "verbose"]:
    best_params.pop(key, None)

for i in range(n_models):

    X_bs, y_bs = resample(
        X_train,
        y_train_co2,
        random_state=200 + i
    )

    model = CatBoostRegressor(
        **best_params,
        random_seed=200 + i,
        verbose=0
    )

    model.fit(X_bs, y_bs)

    cat_preds.append(model.predict(X_test))

cat_preds = np.array(cat_preds)

cat_mean_pred = cat_preds.mean(axis=0)
cat_std_pred  = cat_preds.std(axis=0)

print("CatBoost uncertainty computed successfully")

print("Mean uncertainty:", cat_std_pred.mean())
print("Max uncertainty:", cat_std_pred.max())

plt.figure(figsize=(6,5))
plt.errorbar(
    y_test["log_CO2"],
    cat_mean_pred,
    yerr=cat_std_pred,
    fmt='o',
    alpha=0.5
)

plt.plot(
    [y_test["log_CO2"].min(), y_test["log_CO2"].max()],
    [y_test["log_CO2"].min(), y_test["log_CO2"].max()],
    'r--'
)

plt.xlabel("True log CO₂ permeability")
plt.ylabel("Predicted log CO₂ permeability")
plt.title("CatBoost Prediction with Uncertainty (Bootstrap)")
plt.show()

