# -*- coding: utf-8 -*-
"""NoteBookD1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Wfrdqh3o22q6lusgkJcROk4FTSLUu8_
"""

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split, KFold
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.ensemble import RandomForestRegressor

import matplotlib.pyplot as plt

import numpy as np
import pandas as pd

X = np.load("X_ecfp_full.npy")
y = pd.read_csv("y_targets_full.xls")

print("X shape:", X.shape) #(n_samples,n_bits)
print("y shape:", y.shape)
print("Target columns:", y.columns.tolist())

print("NaNs in X:", np.isnan(X).sum())
print("NaNs in y:", y.isna().sum().sum()) #data integrity #no missing values

y.hist(bins=30, figsize=(10,4))
plt.suptitle("Distribution of log-permeability targets") #check for continuous distribution, extreme values
plt.show()

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("Train samples:", X_train.shape[0])
print("Test samples:", X_test.shape[0])

rf = RandomForestRegressor(

    random_state=42,
    n_estimators=200,
    n_jobs=-1


)

rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

r2 = r2_score(y_test, y_pred, multioutput='raw_values') # how well a statistical model predicts an outcome.
mae = mean_absolute_error(y_test, y_pred, multioutput='raw_values')# average absolute error between predicted and actual value


for i, col in enumerate(y.columns):
    print(f"{col}: R2={r2[i]:.3f}, MAE={mae[i]:.3f}")

plt.figure(figsize=(5,5))
plt.scatter(y_test['log_CO2'], y_pred[:,0], alpha=0.6)
plt.plot([y_test['log_CO2'].min(), y_test['log_CO2'].max()],
         [y_test['log_CO2'].min(), y_test['log_CO2'].max()],
         'r--')
plt.xlabel("True log_CO2")
plt.ylabel("Predicted log_CO2")
plt.title("Random Forest: CO2 Permeability")
plt.show()

baseline_results = {
    "log_CO2": {"R2": r2[0], "MAE": mae[0]},
    "log_N2": {"R2": r2[1], "MAE": mae[1]},
    "log_O2": {"R2": r2[2], "MAE": mae[2]},
}

!pip install xgboost

import numpy as np
import pandas as pd

from xgboost import XGBRegressor

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

import matplotlib.pyplot as plt

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

xgb_models = {}

for col in y.columns: # one model per gas
    model = XGBRegressor(
        n_estimators=200,
        max_depth=8,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        objective="reg:squarederror",
        random_state=42,
        n_jobs=-1
    )

    model.fit(X_train, y_train[col])
    xgb_models[col] = model

y_pred_xgb = np.column_stack([
    xgb_models[col].predict(X_test) for col in y.columns
])

r2 = r2_score(y_test, y_pred_xgb, multioutput="raw_values")
mae = mean_absolute_error(y_test, y_pred_xgb, multioutput="raw_values")

for i, col in enumerate(y.columns):
    print(f"{col}: R2={r2[i]:.3f}, MAE={mae[i]:.3f}")

plt.figure(figsize=(5,5))
plt.scatter(y_test['log_CO2'], y_pred_xgb[:,0], alpha=0.6)

plt.plot(
    [y_test['log_CO2'].min(), y_test['log_CO2'].max()],
    [y_test['log_CO2'].min(), y_test['log_CO2'].max()],
    'r--'
)

plt.xlabel("True log_CO2")
plt.ylabel("Predicted log_CO2")
plt.title("XGBoost: CO2 Permeability")
plt.show()

xgb_results = {
    "log_CO2": {"R2": r2[0], "MAE": mae[0]},
    "log_N2": {"R2": r2[1], "MAE": mae[1]},
    "log_O2": {"R2": r2[2], "MAE": mae[2]},
}

!pip install catboost

from catboost import CatBoostRegressor

cat_model = CatBoostRegressor(
    iterations=200,
    learning_rate=0.05,
    depth=8,
    loss_function='MultiRMSE',
    random_seed=42,
    verbose=0
)

cat_model.fit(X_train, y_train)

y_pred_cat = cat_model.predict(X_test)

from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

r2 = r2_score(y_test, y_pred_cat, multioutput='raw_values')
mae = mean_absolute_error(y_test, y_pred_cat, multioutput='raw_values')


for i, col in enumerate(y.columns):
    print(f"{col}: R2={r2[i]:.3f}, MAE={mae[i]:.3f}")

import matplotlib.pyplot as plt

plt.figure(figsize=(5,5))
plt.scatter(y_test['log_CO2'], y_pred_cat[:,0], alpha=0.6)
plt.plot(
    [y_test['log_CO2'].min(), y_test['log_CO2'].max()],
    [y_test['log_CO2'].min(), y_test['log_CO2'].max()],
    'r--'
)

plt.xlabel("True log_CO2")
plt.ylabel("Predicted log_CO2")
plt.title("CatBoost: CO2 Permeability")
plt.show()

def get_metrics(y_true, y_pred, model_name):
    r2 = r2_score(y_true, y_pred, multioutput="raw_values")
    mae = mean_absolute_error(y_true, y_pred, multioutput="raw_values")
    rmse = np.sqrt(mean_squared_error(y_true, y_pred, multioutput="raw_values"))

    return {
        "Model": model_name,
        "R2_log_CO2": r2[0],
        "R2_log_N2":  r2[1],
        "R2_log_O2":  r2[2],
        "MAE_log_CO2": mae[0],
        "MAE_log_N2":  mae[1],
        "MAE_log_O2":  mae[2],
        "RMSE_log_CO2": rmse[0],
        "RMSE_log_N2":  rmse[1],
        "RMSE_log_O2":  rmse[2],
    }

rf_results = get_metrics(y_test, y_pred, "RandomForest")

xgb_results = get_metrics(y_test, y_pred_xgb, "XGBoost")

cat_results = get_metrics(y_test, y_pred_cat, "CatBoost")

results_df = pd.DataFrame([
    rf_results,
    xgb_results,
    cat_results
])

results_df

r2_table = results_df[
    ["Model", "R2_log_CO2", "R2_log_N2", "R2_log_O2"]
]

r2_table

from sklearn.model_selection import KFold

def cross_validate_model(model_fn, X, y, n_splits=5):
    """
    model_fn: function that returns a fresh model
    X, y: training data
    """
    kf = KFold(n_splits=n_splits, shuffle=True, random_state=42)

    r2_scores = []

    for train_idx, val_idx in kf.split(X):
        X_tr, X_val = X[train_idx], X[val_idx]
        y_tr, y_val = y.iloc[train_idx], y.iloc[val_idx]

        model = model_fn()
        model.fit(X_tr, y_tr)

        y_val_pred = model.predict(X_val)
        r2 = r2_score(y_val, y_val_pred, multioutput="raw_values")

        r2_scores.append(r2)

    r2_scores = np.array(r2_scores)

    return r2_scores.mean(axis=0), r2_scores.std(axis=0)

def rf_model():
    return RandomForestRegressor(
        n_estimators=200,
        random_state=42,
        n_jobs=-1
    )

rf_cv_mean, rf_cv_std = cross_validate_model( # how well a ML model performs on unseen data while preventing overfitting.
    rf_model, X_train, y_train, n_splits=5
)

print("Random Forest CV R2:")
for i, col in enumerate(y.columns):
    print(f"{col}: {rf_cv_mean[i]:.3f} ± {rf_cv_std[i]:.3f}")

def xgb_model():
    return XGBRegressor(
        n_estimators=200,
        max_depth=8,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        objective="reg:squarederror",
        random_state=42,
        n_jobs=-1
    )

xgb_cv_mean, xgb_cv_std = cross_validate_model(
    xgb_model, X_train, y_train, n_splits=5
)

print("XGBoost CV R2:")
for i, col in enumerate(y.columns):
    print(f"{col}: {xgb_cv_mean[i]:.3f} ± {xgb_cv_std[i]:.3f}")

def cat_model():
    return CatBoostRegressor(
        iterations=200,
        learning_rate=0.05,
        depth=8,
        loss_function='MultiRMSE',
        random_seed=42,
        verbose=0
    )

cat_cv_mean, cat_cv_std = cross_validate_model(
    cat_model, X_train, y_train, n_splits=5
)

print("CatBoost CV R2:")
for i, col in enumerate(y.columns):
    print(f"{col}: {cat_cv_mean[i]:.3f} ± {cat_cv_std[i]:.3f}")

cv_results = pd.DataFrame({
    "Model": ["RandomForest", "XGBoost", "CatBoost"],
    "CV_R2_log_CO2": [rf_cv_mean[0], xgb_cv_mean[0], cat_cv_mean[0]],
    "CV_R2_log_N2":  [rf_cv_mean[1], xgb_cv_mean[1], cat_cv_mean[1]],
    "CV_R2_log_O2":  [rf_cv_mean[2], xgb_cv_mean[2], cat_cv_mean[2]],
})

cv_results

import numpy as np
import matplotlib.pyplot as plt

rf_importance = best_rf.feature_importances_

top_n = 20
indices = np.argsort(rf_importance)[-top_n:][::-1]

plt.figure(figsize=(8, 6))
plt.barh(range(top_n), rf_importance[indices][::-1])
plt.yticks(range(top_n), [f"Bit {i}" for i in indices][::-1])
plt.xlabel("Feature Importance")
plt.title("Random Forest Feature Importance (Top 20 ECFP Bits)")
plt.tight_layout()
plt.show()

