# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rh2_75ea7d38imd3ZTaL3ebxApVdH0u1
"""

import numpy as np # numerical operations
import pandas as pd # operation with tabular data

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error #r2-how well a model explains a variation in the dependent variable. #mae- it measures average absolute difference between actual and predicted value #rmse-square root of mae
from sklearn.ensemble import RandomForestRegressor

import matplotlib.pyplot as plt

import numpy as np
import pandas as pd

X = np.load("X_ecfp_full.npy")
y = pd.read_csv("y_targets_full.xls")

print("X shape:", X.shape) #(n_samples,n_bits)
print("y shape:", y.shape)
print("Target columns:", y.columns.tolist())

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("Train samples:", X_train.shape[0])
print("Test samples:", X_test.shape[0])

y_train_co2 = y_train['log_CO2']
y_test_co2 = y_test['log_CO2']

pip install catboost

from catboost import CatBoostRegressor

from catboost import CatBoostRegressor
from sklearn.model_selection import RandomizedSearchCV

cat = CatBoostRegressor(
    loss_function="RMSE",
    random_seed=42,
    verbose=0
)

param_dist = {
    "iterations": [200, 300], #number of trees to be created
    "depth": [6, 8],
    "learning_rate": [0.05, 0.1], # how quickly model runs
    "l2_leaf_reg": [3, 5] #reg parameter to reduce overfitting
}

cat_search = RandomizedSearchCV(
    estimator=cat,
    param_distributions=param_dist,
    n_iter=6,
    scoring="r2",
    n_jobs=-1, #use all cpu cores
    verbose=2,
    random_state=42
)

cat_search.fit(X_train, y_train_co2)

best_cat = cat_search.best_estimator_

y_pred_cat = best_cat.predict(X_test)

from sklearn.metrics import r2_score, mean_absolute_error

print("CatBoost CO2 Test R2:", r2_score(y_test_co2, y_pred_cat))
print("CatBoost CO2 Test MAE:", mean_absolute_error(y_test_co2, y_pred_cat))

from xgboost import XGBRegressor

xgb = XGBRegressor(
    objective="reg:squarederror",
    random_state=42,
    n_jobs=-1
)

param_dist = {
    "n_estimators": [300, 500, 700],
    "max_depth": [4, 6, 8],
    "learning_rate": [0.03, 0.05, 0.1],
    "subsample": [0.8, 1.0], #fraction of training samples used for each tree
    "colsample_bytree": [0.8, 1.0] #fraction of features used by building each tree
}

from sklearn.model_selection import RandomizedSearchCV

xgb_search = RandomizedSearchCV(
    estimator=xgb,
    param_distributions=param_dist,
    n_iter=15,
    cv=5,
    scoring="r2",
    n_jobs=-1,
    verbose=2,
    random_state=42
)

xgb_search.fit(X_train, y_train_co2)

best_xgb = xgb_search.best_estimator_

y_pred_xgb = best_xgb.predict(X_test)

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

r2_xgb = r2_score(y_test_co2, y_pred_xgb)

mae_xgb = mean_absolute_error(y_test_co2, y_pred_xgb)

print(f"XGBoost CO2 Test R2: {r2_xgb:.3f}")

print(f"XGBoost CO2 Test MAE: {mae_xgb:.3f}")

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV

rf = RandomForestRegressor(
    random_state=42,
    n_jobs=-1
)

param_dist = {
    "n_estimators": [200, 300, 400],
    "max_depth": [None, 20],
    "min_samples_split": [2, 5], # minimum samples needed to split a node
    "min_samples_leaf": [1, 2], # minimum samples required at leaf nodes
    "max_features": ["sqrt"]
}

random_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_dist,
    n_iter=10,
    cv=5,
    scoring="r2",
    n_jobs=-1,
    verbose=2,
    random_state=42
)

random_search.fit(X_train, y_train_co2)

best_rf_co2 = random_search.best_estimator_

print("Best hyperparameters:")
print(random_search.best_params_)

print("Best CV R2 score:")
print(random_search.best_score_)

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

y_pred_co2 = best_rf_co2.predict(X_test)

r2 = r2_score(y_test_co2, y_pred_co2)

mae = mean_absolute_error(y_test_co2, y_pred_co2)

print(f"CO2 Test R2: {r2:.3f}")

print(f"CO2 Test MAE: {mae:.3f}")

# ===== Metrics =====
def compute_metrics(y_true, y_pred, name):
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mae = mean_absolute_error(y_true, y_pred)

    # MASE (Mean Absolute Scaled Error)
    naive_forecast = np.mean(np.abs(np.diff(y_true)))
    mase = mae / naive_forecast

    print(f"\n{name} Metrics:")
    print(f"RMSE: {rmse:.4f}")
    print(f"MAE : {mae:.4f}")
    print(f"MASE: {mase:.4f}") #MASE- mean absolute error scaled by average absolute error of a naive baseline model
    #how good our model is compared to a very simple prediction method.

# Call for each model
compute_metrics(y_test_co2.values, y_pred_co2, "Random Forest")
compute_metrics(y_test_co2.values, y_pred_xgb, "XGBoost")
compute_metrics(y_test_co2.values, y_pred_cat, "CatBoost")

import matplotlib.pyplot as plt

def plot_residuals(y_true, y_pred, title):
    residuals = y_true - y_pred

    print("\n" + "="*40)
    print(title)
    print("="*40)

    plt.figure(figsize=(6,5), dpi=500)

    # 🔴 Scatter: light red fill + dark red border
    plt.scatter(
        y_pred,
        residuals,
        s=70,
        facecolors='#fcbba1',   # light red
        edgecolors='#cb181d',   # dark red border
        linewidths=1.5,
        alpha=0.9
    )

    # 🔵 Dark blue reference line
    plt.axhline(
        0,
        linestyle='--',
        color = '#08306b',   # deeper blue (already close)
        linewidth = 3       # slightly thicker
    )

    # Labels and title
    plt.xlabel("Predicted values", fontsize=24, fontweight='bold')
    plt.ylabel("Residuals", fontsize=24, fontweight='bold')
    plt.title(title, fontsize=24, fontweight='bold')

    # Tick size
    plt.xticks(fontsize=20)
    plt.yticks(fontsize=20)

    # Border thickness
    ax = plt.gca()
    for spine in ax.spines.values():
        spine.set_linewidth(2)

    plt.tight_layout()
    plt.show()

plot_residuals(y_test_co2.values, y_pred_co2, "RF Residuals vs Predicted")

plot_residuals(y_test_co2.values, y_pred_xgb, "XGB Residuals vs Predicted")

plot_residuals(y_test_co2.values, y_pred_cat, "CAT Residuals vs Predicted")

import seaborn as sns #statistical data analysis

import numpy as np
import matplotlib.pyplot as plt

# Get importance scores
xgb_importance = best_xgb.feature_importances_

top_n = 20
indices = np.argsort(xgb_importance)[-top_n:][::-1]

# Light color palette
colors = plt.cm.Set3(np.linspace(0, 1, top_n))

plt.figure(figsize=(12, 10), dpi=500)

# Bar plot
plt.barh(
    range(top_n),
    xgb_importance[indices][::-1],
    color=colors[::-1],
    edgecolor='black',
    linewidth=1.2
)

# Y labels
plt.yticks(
    range(top_n),
    [f"Bit {i}" for i in indices][::-1],
    fontsize=20
)

# X ticks
plt.xticks(fontsize=20)

# Labels
plt.xlabel("Feature Importance", fontsize=28, fontweight='bold')
plt.ylabel("ECFP Bits", fontsize=28, fontweight='bold')

# Title
plt.title(
    "XGBoost Feature Importance (Top 20 ECFP Bits)",
    fontsize=30,
    fontweight='bold',
    pad=20
)

# Border thickness
ax = plt.gca()
for spine in ax.spines.values():
    spine.set_linewidth(2)

# Layout adjustment (same as RF)
plt.subplots_adjust(left=0.35, right=0.95, top=0.90, bottom=0.15)

plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Get importance scores
cat_importance = best_cat.get_feature_importance()

top_n = 20
indices = np.argsort(cat_importance)[-top_n:][::-1]

# Light color palette
colors = plt.cm.Set3(np.linspace(0, 1, top_n))

plt.figure(figsize=(12, 10), dpi=500)

# Bar plot
plt.barh(
    range(top_n),
    cat_importance[indices][::-1],
    color=colors[::-1],
    edgecolor='black',
    linewidth=1.2
)

# Y-axis labels
plt.yticks(
    range(top_n),
    [f"Bit {i}" for i in indices][::-1],   # 🔥 consistent naming
    fontsize=20
)

# X-axis ticks
plt.xticks(fontsize=20)

# Axis labels
plt.xlabel("Feature Importance", fontsize=28, fontweight='bold')
plt.ylabel("ECFP Bits", fontsize=28, fontweight='bold')

# Title
plt.title(
    "CatBoost Feature Importance (Top 20 ECFP Bits)",
    fontsize=30,
    fontweight='bold',
    pad=20
)

# Border thickness
ax = plt.gca()
for spine in ax.spines.values():
    spine.set_linewidth(2)

# Layout adjustment
plt.subplots_adjust(left=0.35, right=0.95, top=0.90, bottom=0.15)

plt.show()

pip install shap

import shap
import matplotlib.pyplot as plt
import numpy as np

# Create explainer
explainer_xgb = shap.TreeExplainer(best_xgb)

# Sample data
X_sample = X_train[:500]

# Compute SHAP values
shap_values_xgb = explainer_xgb.shap_values(X_sample)

# 🔥 Create figure FIRST (500 DPI)
plt.figure(figsize=(12,8), dpi=500)

# 🔥 SHAP plot with ONLY TOP 10 features
shap.summary_plot(
    shap_values_xgb,
    X_sample,
    feature_names=[f"ECFP_{i}" for i in range(X.shape[1])],
    max_display=10,
    show=False
)

# Get axis
ax = plt.gca()

# Axis labels
ax.set_xlabel("SHAP value", fontsize=24, fontweight='bold')
ax.set_ylabel("ECFP Bits", fontsize=22, fontweight='bold')

# X-axis ticks
ax.set_xticks(np.arange(-1.5, 1.0, 0.5))

# Tick sizes
ax.tick_params(axis='x', labelsize=20)
ax.tick_params(axis='y', labelsize=18)

# Vertical reference line
ax.axvline(0, color='black', linewidth=2)

# Border thickness
for spine in ax.spines.values():
    spine.set_linewidth(2)

# Colorbar styling
cbar = plt.gcf().axes[-1]
cbar.tick_params(labelsize=16)
cbar.set_ylabel("Feature value", fontsize=18, fontweight='bold')

# Layout fix
plt.subplots_adjust(left=0.32, right=0.88, top=0.95, bottom=0.15)

plt.show()

import numpy as np

# Individual tree predictions
rf_tree_preds = np.array([
    tree.predict(X_test) for tree in best_rf_co2.estimators_
])

# Mean prediction
rf_mean_pred = rf_tree_preds.mean(axis=0)

# Uncertainty = standard deviation across trees
rf_std_pred = rf_tree_preds.std(axis=0)

print("RF prediction shape:", rf_mean_pred.shape)
print("RF uncertainty shape:", rf_std_pred.shape)

import matplotlib.pyplot as plt
import numpy as np   #uncertainty estimation- used to evaluate the confidence of the model prediction

plt.figure(figsize=(7,6), dpi=500)

# 🔵 Scatter with uncertainty (error bars)
plt.errorbar(
    y_test['log_CO2'],
    rf_mean_pred,
    yerr=rf_std_pred,
    fmt='o',
    markersize=6,
    markerfacecolor='#c6dbef',   # light blue inside
    markeredgecolor='#08519c',   # dark blue border
    markeredgewidth=1.2,
    ecolor='#6baed6',            # error bar color
    elinewidth=1,
    alpha=0.7
)

#  Perfect prediction line
min_val = 0
max_val = max(y_test['log_CO2'].max(), rf_mean_pred.max())

plt.plot(
    [min_val, max_val],
    [min_val, max_val],
    linestyle='--',
    color='#cb181d',
    linewidth=2
)

# 🔥 Axis limits
plt.xlim(0, max_val)
plt.ylim(0, max_val)

# 🔥 Labels
plt.xlabel("True permeability", fontsize=24, fontweight='bold')
plt.ylabel("Predicted permeability", fontsize=24, fontweight='bold')

# 🔥 Title
plt.title("Random Forest Prediction with Uncertainty", fontsize=26, fontweight='bold', pad=15)

# 🔥 Tick size
plt.xticks(fontsize=20)
plt.yticks(fontsize=20)

# 🔥 Border thickness
ax = plt.gca()
for spine in ax.spines.values():
    spine.set_linewidth(2)

# 🔥 Grid
plt.grid(alpha=0.3)

# 🔥 Layout fix
plt.subplots_adjust(left=0.28, bottom=0.18, top=0.88)

plt.show()

from sklearn.utils import resample
import numpy as np

# number of bootstrap models
n_models = 20
xgb_preds = []

# get tuned parameters safely
best_params = best_xgb.get_params()

# remove conflicting keys
for key in ["objective", "random_state", "n_jobs"]:
    best_params.pop(key, None)

for i in range(n_models):

    # bootstrap resample
    X_bs, y_bs = resample(
        X_train,
        y_train_co2,
        random_state=100 + i
    )

    # rebuild model with tuned params
    model = XGBRegressor(
        **best_params,
        objective="reg:squarederror",
        random_state=100 + i,
        n_jobs=-1
    )

    model.fit(X_bs, y_bs)

    # predict
    xgb_preds.append(model.predict(X_test))

# convert to array
xgb_preds = np.array(xgb_preds)

# mean & uncertainty
xgb_mean_pred = xgb_preds.mean(axis=0)
xgb_std_pred  = xgb_preds.std(axis=0)

print("XGBoost uncertainty computed successfully")

import joblib

joblib.dump(best_xgb, "final_xgb_surrogate_CO2.pkl") #save the best model to disk

import pandas as pd

original_data = pd.read_excel("dataset.xls") # load the dataset


print(original_data.columns)

print("X shape:", X.shape) # print the feature matrix

filtered_data = original_data[
    original_data[["CO2", "N2", "O2"]].notna().all(axis=1) # filter the rows with gas data
].reset_index(drop=True)

print(len(filtered_data))

assert len(filtered_data) == X.shape[0]

results_all = pd.DataFrame({ # create a new table with values smiles,type ,predict co2
    "SMILES": filtered_data["SMILES"].values,
    "Type": filtered_data["Type"].values,
    "Pred_log_CO2": best_xgb.predict(X)
})

results_all["True_log_CO2"] = np.log10(filtered_data["CO2"].values) #add true value to new table

results_all.to_csv("xgb_predictions_all_polymers.csv", index=False) #add result to csv file

results_all.groupby("Type").size() #group the res by Type

results_all.columns

exp_data = results_all[results_all["Type"] == "Experimental"]
ga_data  = results_all[results_all["Type"] == "Genetic Algorithm"] # grp them by type

results_all["Pred_log_CO2"].isna().sum() # check if NA is present

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(7,5))

sns.kdeplot(exp_data["Pred_log_CO2"], label="Experimental", fill=True)
sns.kdeplot(ga_data["Pred_log_CO2"], label="GA-generated", fill=True) # kde is kernel density estimation is a smooth distribution function

plt.xlabel("Predicted log CO₂ Permeability")
plt.ylabel("Density")
plt.legend()
plt.title("Distribution of Predicted CO₂ Permeability")
plt.tight_layout()
plt.show()

# Train or load N2 model (same hyperparameters)
final_xgb_N2 = XGBRegressor(
    n_estimators=400,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    min_child_weight=1,
    objective="reg:squarederror",
    random_state=42,
    n_jobs=-1
)

final_xgb_N2.fit(X, y["log_N2"]) # train a tuned xgboost model for predicting log_n2

# Predict for ALL polymers
results_all["Pred_log_N2"] = final_xgb_N2.predict(X)

results_all["Pred_log_CO2_N2"] = (
    results_all["Pred_log_CO2"] - results_all["Pred_log_N2"] # predict selectivity
)

results_all["Is_GA"] = (results_all["Type"] == "Genetic Algorithm").astype(int) # create a label 0- experimental and  1- ga

plt.figure(figsize=(6,5))

sc = plt.scatter(
    results_all["Pred_log_CO2"], # permeability
    results_all["Pred_log_CO2_N2"], # selectivity
    c=results_all["Is_GA"],
    cmap="coolwarm",
    alpha=0.7
)

plt.xlabel("Predicted log CO₂ Permeability")
plt.ylabel("Predicted log(CO₂/N₂) Selectivity")
plt.title("Permeability–Selectivity Trade-off")

cbar = plt.colorbar(sc)
cbar.set_ticks([0, 1])
cbar.set_ticklabels(["Experimental", "GA-generated"])

plt.tight_layout()
plt.show()

from xgboost import XGBRegressor



# Train N2 model
xgb_n2 = XGBRegressor( # run a tuned model to predict log_n2 and log_o2
    n_estimators=400,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    min_child_weight=1,
    objective="reg:squarederror",
    random_state=42,
    n_jobs=-1
)

xgb_n2.fit(X, y["log_N2"])


# Train O2 model
xgb_o2 = XGBRegressor(
    n_estimators=400,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    min_child_weight=1,
    objective="reg:squarederror",
    random_state=42,
    n_jobs=-1
)

xgb_o2.fit(X, y["log_O2"])

pred_co2 = best_xgb.predict(X)
pred_n2  = xgb_n2.predict(X)
pred_o2  = xgb_o2.predict(X)

selectivity_co2_n2 = pred_co2 - pred_n2
selectivity_co2_o2 = pred_co2 - pred_o2 # selectivity

import pandas as pd

results_all = pd.DataFrame({ # create a table
    "Pred_log_CO2": pred_co2,
    "Pred_log_N2": pred_n2,
    "Pred_log_O2": pred_o2,
    "Pred_log_CO2_N2": selectivity_co2_n2,
    "Pred_log_CO2_O2": selectivity_co2_o2
})

import matplotlib.pyplot as plt

# Create figure
plt.figure(figsize=(7, 6), dpi=500)

# Scatter plot
plt.scatter(
    results_all["Pred_log_CO2"],
    results_all["Pred_log_CO2_N2"],
    s=60,
    facecolors='#c6dbef',
    edgecolors='#08519c',
    linewidths=1.2,
    alpha=0.9
)

# Axis labels
plt.xlabel(
    "Predicted log CO₂ Permeability",
    fontsize=16,
    fontweight='bold'
)

plt.ylabel(
    "Predicted log(CO₂/N₂) Selectivity",
    fontsize=16,
    fontweight='bold'
)



# Tick font sizes
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)


plt.xlim(-2, 5)
plt.ylim(-1, 2.5)

# Make axes thicker
ax = plt.gca()
for spine in ax.spines.values():
    spine.set_linewidth(2)

# Grid
plt.grid(alpha=0.3)

# Automatically adjust spacing so nothing is cut
plt.tight_layout()

# Show plot
plt.show()

# Define thresholds
high_perm = results_all["Pred_log_CO2"] > 3 # selecting candidates with high permeability (1000 barrer)
high_sel  = results_all["Pred_log_CO2_N2"] > 1.5 # selecting candidates with high selectivity (31.6)

top_candidates = results_all[high_perm & high_sel]

print("Number of top candidates:", len(top_candidates))

top_candidates.sort_values(
    by=["Pred_log_CO2", "Pred_log_CO2_N2"],
    ascending=False
).head(10)

import numpy as np
import matplotlib.pyplot as plt

# Data
x = results_all["Pred_log_CO2"]
y = results_all["Pred_log_CO2"] - results_all["Pred_log_N2"]

# Create figure
plt.figure(figsize=(7, 6), dpi=500)

# Scatter plot
plt.scatter(
    x,
    y,
    s=50,
    facecolors='#c6dbef',
    edgecolors='#08519c',
    linewidths=1.2,
    alpha=0.9
)

# Robeson Upper Bound (2008)
x_line = np.linspace(-2, 4.5, 300)
robeson_line = 2.594 - 0.346 * x_line

plt.plot(
    x_line,
    robeson_line,
    '--',
    color='#cb181d',
    linewidth=2,
    label='Robeson Upper Bound (2008)'
)

# Axis labels
plt.xlabel(
    "Predicted log CO₂ Permeability",
    fontsize=16,
    fontweight='bold'
)

plt.ylabel(
    "Predicted log(CO₂/N₂) Selectivity",
    fontsize=16,
    fontweight='bold'
)

plt.xlim(-2, 5)
plt.ylim(-1, 2.5)

# Tick font size
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)

# Legend (top-right, smaller)
plt.legend(
    loc='upper right',
    fontsize=10,
    frameon=True,
    fancybox=True,
    framealpha=0.9,
    borderpad=0.4,
    handlelength=2
)

# Grid
plt.grid(alpha=0.3)

# Thicker borders
ax = plt.gca()
for spine in ax.spines.values():
    spine.set_linewidth(2)

# Automatically adjust spacing
plt.tight_layout()

# Show figure
plt.show()

# Robeson bound equation
def robeson_bound(x):
    return 2.594 - 0.346 * x #1=intercept 0.5=slope

# Calculate selectivity
results_all["Pred_log_Selectivity"] = (
    results_all["Pred_log_CO2"] - results_all["Pred_log_N2"]
)

# Calculate Robeson limit for each sample
results_all["Robeson_limit"] = robeson_bound(results_all["Pred_log_CO2"])

# Distance from bound
results_all["Distance_from_bound"] = (
    results_all["Pred_log_Selectivity"] - results_all["Robeson_limit"] #>0 above bound else below bound
)

# Identify promising candidates
top_candidates = results_all[
    results_all["Distance_from_bound"] > 0
]

print("Number of candidates above Robeson bound:", len(top_candidates))
top_candidates.head()

from sklearn.utils import resample
from xgboost import XGBRegressor
import numpy as np

n_models = 20 # multiple models # distribution of predictions
xgb_preds = []

# get tuned parameters
best_params = best_xgb.get_params()

# remove conflicting keys
for key in ["objective", "random_state", "n_jobs"]:
    best_params.pop(key, None)

for i in range(n_models):

    # bootstrap resampling from training set
    X_bs, y_bs = resample( # create a new training dataset each time by samling with replacement and using diff data distribution
        X_train,
        y_train_co2,
        random_state=100 + i
    )

    # rebuild model
    model = XGBRegressor(
        **best_params,
        objective="reg:squarederror",
        random_state=100 + i,
        n_jobs=-1
    )

    model.fit(X_bs, y_bs)

    # predict FULL dataset
    preds = model.predict(X)
    xgb_preds.append(preds)

# convert to array
xgb_preds = np.array(xgb_preds) #[20 models,N_samples]

# compute mean and uncertainty
mean_co2 = xgb_preds.mean(axis=0)
uncertainty_co2 = xgb_preds.std(axis=0)

results_all["Pred_log_CO2"] = mean_co2 #stores the result
results_all["Uncertainty_CO2"] = uncertainty_co2

threshold = results_all["Uncertainty_CO2"].quantile(0.75)# 75% of the uncertainty 25% of the unceratinty are removed

robust_candidates = results_all[
    results_all["Uncertainty_CO2"] < threshold # keep only robust candidates (keep a polymer when a model is confident)
]

top_threshold = results_all["Pred_log_CO2"].quantile(0.95) #select top 5% performers

top_candidates = results_all[
    results_all["Pred_log_CO2"] > top_threshold # high-permeability polymers
]

# Robust + High Performance +low uncertain
final_candidates = top_candidates[
    top_candidates["Uncertainty_CO2"] < threshold
]

final_candidates.head()

robust_candidates = final_candidates[
    final_candidates["Pred_log_Selectivity"] > final_candidates["Robeson_limit"] #above robeson limit
]

robust_candidates.head()

final_candidates["Score"] = (
    final_candidates["Pred_log_CO2"] +
    final_candidates["Pred_log_Selectivity"] -
    5 * final_candidates["Uncertainty_CO2"]
)

top_ranked = final_candidates.sort_values("Score", ascending=False)#high to low

top_ranked.head(10)

print(filtered_data.columns.tolist())

# ============================================================
# FINAL MULTI-OBJECTIVE OPTIMIZATION PIPELINE
# ============================================================

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# ------------------------------------------------------------
# 1. Correct Pareto-efficient function
# ------------------------------------------------------------

def is_pareto_efficient(points):
    n_points = points.shape[0]
    is_efficient = np.ones(n_points, dtype=bool)

    for i in range(n_points):
        if not is_efficient[i]:
            continue

        dominated = np.any(
            np.all(points >= points[i], axis=1) &
            np.any(points > points[i], axis=1)
        )

        if dominated:
            is_efficient[i] = False

    return is_efficient


# ------------------------------------------------------------
# 2. Optimization matrix
# ------------------------------------------------------------

cost_matrix = np.column_stack([
    results_all["Pred_log_CO2"].values,
    results_all["Pred_log_Selectivity"].values,
    -results_all["Uncertainty_CO2"].values
])

# ------------------------------------------------------------
# 3. Pareto candidates
# ------------------------------------------------------------

pareto_mask = is_pareto_efficient(cost_matrix)

pareto_candidates = results_all[pareto_mask].copy()
print("="*60)
print("Pareto candidates :", len(pareto_candidates))

# ------------------------------------------------------------
# 4. Candidates above Robeson bound
# ------------------------------------------------------------

pareto_above = pareto_candidates[
    pareto_candidates["Distance_from_bound"] > 0
].copy()

print("Above Robeson :", len(pareto_above))

# ------------------------------------------------------------
# 5. Robust candidates
# ------------------------------------------------------------

if len(pareto_above) == 0:

    print("\nNo membrane above Robeson bound.")
    robust_pareto = pareto_candidates.copy()

else:

    threshold = pareto_above["Uncertainty_CO2"].quantile(0.75)

    robust_pareto = pareto_above[
        pareto_above["Uncertainty_CO2"] <= threshold
    ].copy()

print("Robust candidates :", len(robust_pareto))

# ------------------------------------------------------------
# 6. Ranking
# ------------------------------------------------------------

if len(robust_pareto):

    scaler = MinMaxScaler()

    score_df = robust_pareto.copy()

    score_df["Norm_CO2"] = scaler.fit_transform(
        score_df[["Pred_log_CO2"]]
    )

    score_df["Norm_Selectivity"] = scaler.fit_transform(
        score_df[["Pred_log_Selectivity"]]
    )

    score_df["Norm_Distance"] = scaler.fit_transform(
        score_df[["Distance_from_bound"]]
    )

    score_df["Norm_Uncertainty"] = 1 - scaler.fit_transform(
        score_df[["Uncertainty_CO2"]]
    )

    score_df["Composite_Score"] = (
        0.35*score_df["Norm_CO2"] +
        0.35*score_df["Norm_Selectivity"] +
        0.20*score_df["Norm_Distance"] +
        0.10*score_df["Norm_Uncertainty"]
    )

    top_final = score_df.sort_values(
        "Composite_Score",
        ascending=False
    ).head(20)

    # Remove old numeric index
    top_final = top_final.reset_index(drop=True)

    print("\nTop 20 Optimized Membranes\n")

    # -------- Display columns available in your dataset --------

    columns_to_show = []

    if "SMILES" in top_final.columns:
        columns_to_show.append("SMILES")

    if "Polymer_Name" in top_final.columns:
        columns_to_show.append("Polymer_Name")

    columns_to_show += [
        "Pred_log_CO2",
        "Pred_log_Selectivity",
        "Distance_from_bound",
        "Uncertainty_CO2",
        "Composite_Score"
    ]

    display(top_final[[

    "Pred_log_CO2",
    "Pred_log_Selectivity",
    "Distance_from_bound",
    "Uncertainty_CO2",
    "Composite_Score"
]])

    # Save CSV
    top_final.to_csv(
        "Top_20_Optimized_Membranes.csv",
        index=False
    )

pareto_candidates.to_csv(
    "Pareto_Optimal_Membranes.csv",
    index=False
)

robust_pareto.to_csv(
    "Robust_Pareto_Membranes.csv",
    index=False
)

print("\nOptimization Completed Successfully.")

print(results_all.columns.tolist())

import matplotlib.pyplot as plt

plt.figure(figsize=(7,6), dpi=500)

# 🔵 All polymers (light + transparent)
plt.scatter(
    results_all["Pred_log_CO2"],
    results_all["Pred_log_Selectivity"],
    s=50,
    facecolors='#c6dbef',   # light blue
    edgecolors='#08519c',   # dark blue border
    linewidths=1.0,
    alpha=0.5,
    label="All Polymers"
)

# 🔴 Pareto front (highlight)
plt.scatter(
    pareto_candidates["Pred_log_CO2"],
    pareto_candidates["Pred_log_Selectivity"],
    s=70,
    facecolors='#fcbba1',   # light red
    edgecolors='#cb181d',   # dark red
    linewidths=1.5,
    alpha=1.0,
    label="Pareto Front"
)

# Labels
plt.xlabel("Predicted log CO₂ Permeability", fontsize=16, fontweight='bold')
plt.ylabel("Predicted log(CO₂/N₂) Selectivity", fontsize=16, fontweight='bold')

plt.xlim(-2, 5)
plt.ylim(-1, 2.5)


# Tick size
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)

# Border thickness
ax = plt.gca()
for spine in ax.spines.values():
    spine.set_linewidth(2)

# Legend
plt.legend(
    fontsize=9,
    loc='lower left',
    frameon=True,
    fancybox=True,
    framealpha=0.9,
    borderpad=0.3,
    handlelength=1.8,
    markerscale=0.9
)

# Grid
plt.grid(alpha=0.3)

# 🔥 Fix clipping (same as before)
plt.subplots_adjust(left=0.30, bottom=0.18, top=0.88)

plt.show()

from sklearn.utils import resample
from xgboost import XGBRegressor
import numpy as np

n_models = 20
xgb_preds_test = []

best_params = best_xgb.get_params()

# remove conflicting keys
for key in ["objective", "random_state", "n_jobs"]:
    best_params.pop(key, None)

for i in range(n_models):

    X_bs, y_bs = resample(
        X_train,
        y_train_co2,
        random_state=100 + i
    )

    model = XGBRegressor(
        **best_params,
        objective="reg:squarederror",
        random_state=100 + i,
        n_jobs=-1
    )

    model.fit(X_bs, y_bs)

    preds_test = model.predict(X_test)
    xgb_preds_test.append(preds_test)

xgb_preds_test = np.array(xgb_preds_test)

mean_pred = xgb_preds_test.mean(axis=0)
uncertainty = xgb_preds_test.std(axis=0)

residuals = y_test_co2.values - mean_pred
abs_residuals = np.abs(residuals)

# ===============================
# Uncertainty Calibration
# ===============================

# Compute scale factor
scale_factor = np.mean(abs_residuals) / np.mean(uncertainty)

print("Uncertainty scale factor:", scale_factor)

# Calibrate uncertainty
uncertainty_calibrated = scale_factor * uncertainty

# Recompute coverage
within_1sigma_cal = np.mean(abs_residuals <= uncertainty_calibrated)
within_2sigma_cal = np.mean(abs_residuals <= 2 * uncertainty_calibrated)

print(f"Calibrated within 1σ: {within_1sigma_cal*100:.2f}%")
print(f"Calibrated within 2σ: {within_2sigma_cal*100:.2f}%")

# Apply calibration globally
results_all["Uncertainty_CO2"] = (
    scale_factor * results_all["Uncertainty_CO2"]
)

import matplotlib.pyplot as plt

plt.figure(figsize=(9,6), dpi=500)   # 🔥 bigger figure

plt.scatter(
    uncertainty_calibrated,
    abs_residuals,
    s=60,
    facecolors='#fcbba1',
    edgecolors='#cb181d',
    linewidths=1.2,
    alpha=0.9
)

# Labels
plt.xlabel("Predicted Uncertainty", fontsize=24, fontweight='bold')
plt.ylabel("Absolute Residual", fontsize=24, fontweight='bold')

# Title
plt.title(
    "Uncertainty Calibration: Residual vs Predicted σ",
    fontsize=26,
    fontweight='bold',
    pad=20   # 🔥 adds spacing from plot
)

# Tick size
plt.xticks(fontsize=20)
plt.yticks(fontsize=20)

# Border
ax = plt.gca()
for spine in ax.spines.values():
    spine.set_linewidth(2)

# Grid
plt.grid(alpha=0.3)

# 🔥 CRITICAL FIX (layout control)
plt.subplots_adjust(left=0.30, bottom=0.20, top=0.85)

plt.show()

# Normalize metrics for fair scoring
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() #noramlize so that one do not dominate the other

score_df = robust_pareto.copy()

score_df[["Norm_CO2"]] = scaler.fit_transform(
    score_df[["Pred_log_CO2"]]
)

score_df[["Norm_Selectivity"]] = scaler.fit_transform(
    score_df[["Pred_log_Selectivity"]]
)

score_df[["Norm_Distance"]] = scaler.fit_transform(
    score_df[["Distance_from_bound"]]
)

# Lower uncertainty is better → invert it because scaler makes larger value
score_df[["Norm_Uncertainty"]] = 1 - scaler.fit_transform(
    score_df[["Uncertainty_CO2"]]
)

score_df["Composite_Score"] = (
    0.35 * score_df["Norm_CO2"] + # 35% importance to norm_co2
    0.35 * score_df["Norm_Selectivity"] +
    0.20 * score_df["Norm_Distance"] +
    0.10 * score_df["Norm_Uncertainty"]
)

top_final = score_df.sort_values(
    by="Composite_Score",
    ascending=False
).head(20)

top_final.reset_index(drop=True, inplace=True)

top_final.head()

report_table = top_final[[
    "Pred_log_CO2",
    "Pred_log_Selectivity",
    "Distance_from_bound",
    "Uncertainty_CO2",
    "Composite_Score"
]]

report_table

report_table.to_csv("Top_20_Optimized_Membranes.csv", index=False)

# Assume membrane thickness (m)
thickness = 100e-9  # 100 nm

# Convert log permeability to permeability
P_CO2 = 10 ** results_all["Pred_log_CO2"]

# Compute permeance
permeance_CO2 = P_CO2 / thickness

results_all["Permeance_CO2"] = permeance_CO2

results_all["TechnoEconomic_Index"] = (
    0.5 * (results_all["Permeance_CO2"] / results_all["Permeance_CO2"].max()) +
    0.4 * (results_all["Pred_log_Selectivity"] / results_all["Pred_log_Selectivity"].max()) -
    0.1 * (results_all["Uncertainty_CO2"] / results_all["Uncertainty_CO2"].max())
)

# Different weight combinations
weight_sets = {
    "Original (0.5,0.4,0.1)": (0.5, 0.4, 0.1),
    "Case 1 (0.4,0.5,0.1)": (0.4, 0.5, 0.1),
    "Case 2 (0.45,0.45,0.1)": (0.45, 0.45, 0.1),
    "Case 3 (0.55,0.35,0.1)": (0.55, 0.35, 0.1)
}

for name, (wP, wS, wU) in weight_sets.items():

    results_all["Composite_Performance_Index"] = (
        wP * (results_all["Permeance_CO2"] / results_all["Permeance_CO2"].max()) +
        wS * (results_all["Pred_log_Selectivity"] / results_all["Pred_log_Selectivity"].max()) -
        wU * (results_all["Uncertainty_CO2"] / results_all["Uncertainty_CO2"].max())
    )

    top = (
        results_all
        .sort_values("Composite_Performance_Index", ascending=False)
        .drop_duplicates(subset=["Permeance_CO2","Pred_log_Selectivity"])
        .head(10)
    )

    print("\n==============================")
    print(name)
    print("==============================")
    print(top.index.tolist())

import matplotlib.pyplot as plt
import numpy as np

# Create figure
plt.figure(figsize=(7, 6), dpi=500)

# Scatter plot (colored by Composite Performance Index)
sc = plt.scatter(
    results_all["Permeance_CO2"],
    results_all["Pred_log_Selectivity"],
    c=results_all["TechnoEconomic_Index"],
    cmap="viridis",
    s=50,
    edgecolors='#08519c',
    linewidths=0.8,
    facecolors='None',
    alpha=0.8,
    vmin=0.0,   # Start colorbar at 0
    vmax=results_all["TechnoEconomic_Index"].max()
)

# Top candidates
top = results_all.sort_values(
    "TechnoEconomic_Index",
    ascending=False
).head(10)

plt.scatter(
    top["Permeance_CO2"],
    top["Pred_log_Selectivity"],
    s=120,
    facecolors='#fcbba1',
    edgecolors='#cb181d',
    linewidths=1.5,
    label="Top Candidates",
    zorder=5
)

# Log scale
plt.xscale("log")

# Colorbar
cbar = plt.colorbar(sc)
cbar.set_label(
    "Composite Performance Index",
    fontsize=16,
    fontweight='bold'
)
cbar.ax.tick_params(labelsize=14)

# Colorbar ticks start at 0
ticks = np.arange(
    0,
    results_all["TechnoEconomic_Index"].max() + 0.1,
    0.1
)
cbar.set_ticks(ticks)

# Axis labels
plt.xlabel(
    "CO₂ Permeance (log scale)",
    fontsize=16,
    fontweight='bold'
)

plt.ylabel(
    "Predicted log(CO₂/N₂) Selectivity",
    fontsize=16,
    fontweight='bold'
)

# Axis limits
plt.ylim(-1, 2.5)

# Tick font size
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)

# Legend (smaller)
plt.legend(
    fontsize=10,
    loc='upper left',
    frameon=True,
    fancybox=True,
    framealpha=0.9
)

# Grid
plt.grid(alpha=0.3)

# Thicker borders
ax = plt.gca()
for spine in ax.spines.values():
    spine.set_linewidth(2)

# Layout
plt.tight_layout()

# Show figure
plt.show()

top = (
    results_all
    .sort_values("TechnoEconomic_Index", ascending=False)
    .drop_duplicates(subset=["Permeance_CO2", "Pred_log_Selectivity"])
    .head(10)
)

print(top[[
    "Permeance_CO2",
    "Pred_log_Selectivity",
    "TechnoEconomic_Index"
]])